version: '3'
services:
  solr:
    image: solr
    hostname: solr
    ports:
     - "9983:9983"
     - "8983:8983"
    volumes:
      - solrdata:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "exec solr start -c -f"
volumes:
  solrdata: